WHENEVER SQLERROR EXIT SQL.SQLCODE;

CREATE USER supportly IDENTIFIED BY "Qwerty_1"
    DEFAULT TABLESPACE SUPPORTLY_TS
    TEMPORARY TABLESPACE TEMP
    PROFILE DEFAULT
    ACCOUNT UNLOCK;

GRANT CONNECT TO supportly;
GRANT RESOURCE TO supportly;
GRANT UNLIMITED TABLESPACE TO supportly;

GRANT ALTER ANY TABLE TO supportly;
GRANT DELETE ANY TABLE TO supportly;
GRANT INSERT ANY TABLE TO supportly;
GRANT UPDATE ANY TABLE TO supportly;
GRANT CREATE ANY TABLE TO supportly;
GRANT CREATE ANY INDEX TO supportly;
GRANT SELECT ANY TABLE TO supportly;
GRANT CREATE ANY SEQUENCE TO supportly;
GRANT DROP ANY INDEX TO supportly;
GRANT CREATE SESSION TO supportly;
GRANT CREATE VIEW TO supportly;

GRANT SELECT_CATALOG_ROLE TO supportly;

EXIT;