CREATE TABLE EMPLOYEE
(
    ID               SERIAL PRIMARY KEY,
    FIRST_NAME       VARCHAR(255) NOT NULL,
    SECOND_NAME      VARCHAR(255),
    LAST_NAME        VARCHAR(255) NOT NULL,
    EMAIL            VARCHAR(255),
    PHONE_NUMBER     BIGINT       NOT NULL,
    DATA_OF_CREATION DATE         NOT NULL
);

CREATE TABLE CLIENT
(
    ID               SERIAL PRIMARY KEY,
    NAME             VARCHAR(255) NOT NULL,
    NIP              VARCHAR(13),
    ADDRESS          VARCHAR(255) NOT NULL,
    CITY             VARCHAR(255) NOT NULL,
    ZIP_CODE         VARCHAR(255) NOT NULL,
    STREET_NUMBER    VARCHAR(255) NOT NULL,
    APARTMENT_NUMBER VARCHAR(255),
    PHONE_NUMBER     VARCHAR(9)   NOT NULL,
    EMAIL            VARCHAR(255) NOT NULL,
    TYPE             VARCHAR(255) NOT NULL
);

CREATE TABLE ACTIVITIES
(
    ID        SERIAL PRIMARY KEY,
    NAME      VARCHAR(255) NOT NULL,
    ATTENTION VARCHAR(255),
    DONE      BIT          NOT NULL
);

CREATE TABLE PARTS_TEMPLATE
(
    ID    SERIAL PRIMARY KEY,
    NAME  VARCHAR(255) NOT NULL,
    PRICE FLOAT        NOT NULL,
    TAX   FLOAT
);

CREATE TABLE ACTIVITIES_TEMPLATE
(
    ID   SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE ROLE
(
    ID          SERIAL PRIMARY KEY,
    NAME        VARCHAR(255) UNIQUE            NOT NULL,
    DESCRIPTION VARCHAR(255)                   NOT NULL,
    CREATED_AT  DATE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT  DATE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE TASK
(
    ID            SERIAL PRIMARY KEY,
    NAME          VARCHAR(255) NOT NULL,
    executionTime DATE,
    DONE          BIT,
    EMPLOYEE_ID   BIGINT,
    CONSTRAINT FK_TASK_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES Employee (ID)
);

CREATE TABLE ADM_USER
(
    ID        SERIAL PRIMARY KEY,
    FULL_NAME VARCHAR(255)                   NOT NULL,
    EMAIL     VARCHAR(100) UNIQUE            NOT NULL,
    PASSWORD  VARCHAR(255)                   NOT NULL,
    CREATE_AT DATE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_AT DATE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    role_id   INT                            NOT NULL,
    CONSTRAINT FK_USER_ROLE FOREIGN KEY (role_id) REFERENCES Role (id)
);


CREATE TABLE PART
(
    ID     SERIAL PRIMARY KEY,
    NAME   VARCHAR(255),
    PRICE  FLOAT,
    TAX    FLOAT,
    AMOUNT INT
);

CREATE TABLE "order"
(
    ID                SERIAL PRIMARY KEY,
    CLIENT_ID         BIGINT,
    DATE_OF_ADMISSION DATE,
    DATE_OF_EXECUTION DATE,
    MAN_HOUR          FLOAT,
    DISTANCE          FLOAT,
    PRIORITY          VARCHAR(255),
    STATUS            VARCHAR(255),
    PERIOD            VARCHAR(255),
    NOTE              VARCHAR(255),
    CONSTRAINT FK_ORDER_CLIENT FOREIGN KEY (CLIENT_ID) REFERENCES Client (ID)
);