CREATE TABLE EMPLOYEE
(
    ID               INT IDENTITY PRIMARY KEY,
    FIRST_NAME       NVARCHAR(255) NOT NULL,
    SECOND_NAME      NVARCHAR(255),
    LAST_NAME        NVARCHAR(255) NOT NULL,
    EMAIL            NVARCHAR(255),
    PHONE_NUMBER     BIGINT        NOT NULL,
    DATA_OF_CREATION DATE          NOT NULL
);

CREATE TABLE CLIENT
(
    ID               INT IDENTITY PRIMARY KEY,
    NAME             NVARCHAR(255) NOT NULL,
    NIP              NVARCHAR(13),
    ADDRESS          NVARCHAR(255) NOT NULL,
    CITY             NVARCHAR(255) NOT NULL,
    ZIP_CODE         NVARCHAR(255) NOT NULL,
    STREET_NUMBER    NVARCHAR(255) NOT NULL,
    APARTMENT_NUMBER NVARCHAR(255),
    PHONE_NUMBER     NVARCHAR(9)   NOT NULL,
    EMAIL            NVARCHAR(255) NOT NULL,
    TYPE             NVARCHAR(255) NOT NULL
);

CREATE TABLE ACTIVITIES
(
    ID        INT IDENTITY PRIMARY KEY,
    NAME      NVARCHAR(255) NOT NULL,
    ATTENTION NVARCHAR(255),
    DONE      BIT           NOT NULL
);

CREATE TABLE PARTS_TEMPLATE
(
    ID    INT IDENTITY PRIMARY KEY,
    NAME  NVARCHAR(255) NOT NULL,
    PRICE FLOAT         NOT NULL,
    TAX   FLOAT
);

CREATE TABLE ACTIVITIES_TEMPLATE
(
    ID   INT IDENTITY PRIMARY KEY,
    NAME NVARCHAR(255) NOT NULL
);

CREATE TABLE ROLE
(
    ID          INT IDENTITY PRIMARY KEY,
    NAME        NVARCHAR(255) UNIQUE            NOT NULL,
    DESCRIPTION NVARCHAR(255)                   NOT NULL,
    CREATED_AT  DATE DEFAULT GETDATE()          NOT NULL,
    UPDATED_AT  DATE DEFAULT GETDATE()          NOT NULL
);

CREATE TABLE TASK
(
    ID            INT IDENTITY PRIMARY KEY,
    NAME          NVARCHAR(255) NOT NULL,
    executionTime DATE,
    DONE          BIT,
    EMPLOYEE_ID   INT,
    CONSTRAINT FK_TASK_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE (ID)
);

CREATE TABLE ADM_USER
(
    ID        INT IDENTITY PRIMARY KEY,
    FULL_NAME NVARCHAR(255)                   NOT NULL,
    EMAIL     NVARCHAR(100) UNIQUE            NOT NULL,
    PASSWORD  NVARCHAR(255)                   NOT NULL,
    CREATE_AT DATE DEFAULT GETDATE()          NOT NULL,
    UPDATE_AT DATE DEFAULT GETDATE()          NOT NULL,
    role_id   INT                             NOT NULL,
    CONSTRAINT FK_USER_ROLE FOREIGN KEY (role_id) REFERENCES ROLE (ID)
);

CREATE TABLE PART
(
    ID     INT IDENTITY PRIMARY KEY,
    NAME   NVARCHAR(255),
    PRICE  FLOAT,
    TAX    FLOAT,
    AMOUNT INT
);

CREATE TABLE [order]
(
    ID                INT IDENTITY PRIMARY KEY,
    CLIENT_ID         INT,
    DATE_OF_ADMISSION DATE,
    DATE_OF_EXECUTION DATE,
    MAN_HOUR          FLOAT,
    DISTANCE          FLOAT,
    PRIORITY          NVARCHAR(255),
    STATUS            NVARCHAR(255),
    PERIOD            NVARCHAR(255),
    NOTE              NVARCHAR(255),
    CONSTRAINT FK_ORDER_CLIENT FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT (ID)
);