CREATE TABLE ORDER_EMPLOYEE
(
    ORDER_ID    NUMBER(19, 0) NOT NULL,
    EMPLOYEE_ID NUMBER(19, 0) NOT NULL,
    CONSTRAINT PK_ORDER_EMPLOYEE PRIMARY KEY (ORDER_ID, EMPLOYEE_ID),
    CONSTRAINT FK_ORDER_EMPLOYEE_ORDER FOREIGN KEY (ORDER_ID)
        REFERENCES "order" (ID)
        ON DELETE CASCADE,
    CONSTRAINT FK_ORDER_EMPLOYEE_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID)
        REFERENCES EMPLOYEE (ID)
        ON DELETE CASCADE
);
