DROP TABLE task CASCADE CONSTRAINTS;

CREATE TABLE task
(
    id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR2(255) NOT NULL,
    execution_time DATE,
    order_id       NUMBER UNIQUE,
    done           NUMBER(1),

    CONSTRAINT fk_task_order FOREIGN KEY (order_id) REFERENCES "ORDER"(id)
);

CREATE TABLE task_employee
(
    task_id     NUMBER NOT NULL,
    employee_id NUMBER NOT NULL,

    PRIMARY KEY (task_id, employee_id),
    CONSTRAINT fk_task_emp_task FOREIGN KEY (task_id) REFERENCES task(id),
    CONSTRAINT fk_task_emp_employee FOREIGN KEY (employee_id) REFERENCES employee(id)
);
