services:
  postgres:
    build:
      context: postgres
      dockerfile: Dockerfile
    image: localhost:32000/conf-postgres:latest
    container_name: supportly-database
    privileged: true
    ports:
      - PORT_DB:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d db_prod"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 30s

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    image: localhost:32000/conf-backend:latest
    container_name: supportly-backend
    env_file:
      - ./backend/backend.env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - PORT_BACKEND:8080
      -


#  frontend: ten działa
#    build:
#      context: ..
#      dockerfile: conf/frontend/Dockerfile
#    container_name: supportly-frontend
#    ports:
#      - "4200:80"


  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   image: localhost:32000/conf-frontend:latest
  #   container_name: angular-frontend
  #   environment:
  #     BACKEND_URL: http://spring-backend:8080
  #   depends_on:
  #     - backend
  #   ports:
  #     - "4200:80"

volumes:
  postgres-data: